### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by DanilaX1** [iterativ/openopc2#23]
hello, I'm trying to install this library on isolated pure python 3.8, a separate virtualnev project in pycharm ide. 

 pip install openopc2
 openopc2 --install
 python -m openopc2 servers
 
The second step already returns an error

I also wanted to ask the commands for working with the library the same as in the original openops, if they are different, then I'm waiting for examples

**Comment by renzop** [comment]
Yea, the install command is not yet implemented. Still in the making. But you can skip it if you want to use openopc2. Are you more interested in the cli functionality or use as python library. The commands will differ a bit to the original openopc, if you type 

python -m openopc2 --help 

you get some info what you can do. If you would like to participate and make some examples that would be great.
