### ISSUE TITLE
Problem with close() method

### ISSUE THREAD

**Issue by LucasCCedge** [iterativ/openopc2#48]
Hi, i recently start to use OpenOPC2 to comunicate with an old OPC server for monitoring porpouses. 

I just put together a minimal working program, with a feel prints and sleeps to see it working. But in practice is basically this: 

```
opc= OpenOPC.client()

opc.connect(opc.servers()[0],'localhost')
TAGs = []
TAGs = opc.read(tags=tag_names, group=opc_group,source='cache')
print(TAGs)
opc.close()
```

This should work just fine i guess. 

I'm able to connect to both simulated and real OPC servers, both in my local machine and in the network. And the script retrieves the Tags values just fine.

The problem is in the opc.close() method. It just crashes the script and gives me this error:

```
Traceback (most recent call last):
  File "C:\Users\lucas.caetano\Desktop\DMZ_collector.py", line 47, in <module>
    opc.close()
  File "C:\Users\lucas.caetano\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\OpenOPC.py", line 272, in close
    self.remove(self.groups())
  File "C:\Users\lucas.caetano\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\OpenOPC.py", line 868, in remove
    for group in groups:
    ^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
```

The method closes the connection with the simulated OPC server as the script crashes. So i know that the method is working some way, it not leaves the connection open so the server closes it in its side. Using opc.close() inside a try statemente i was able to close the connection and keep the script running.

So, i want to know, is this the normal behaviour of the close() method? Should i always use it inside a try statement? Or am i doing something wrong?

**Comment by renzop** [comment]
Can you put programming questions on Stackoverflow i think it is the better place for that. BTW. the variable tag_names is not defined in your code. You can tag the question with open-opc to make search easyier.
