### ISSUE TITLE
Connection timed out   was occur when access to UNICORN OPC server

### ISSUE THREAD

**Issue by c-s-u** [iterativ/openopc2#50]
Hi

I'm sorry if I'm wrong to ask you individually.
I was having trouble connecting to the [UNICORN OPC server](https://cdn.cytivalifesciences.com/api/public/content/digi-17991-original), so I would appreciate it if you could support the connection method.

I got following error
```
jovyan@jupyter-182872:~$ OPC_CLASS=OPC.Automation
jovyan@jupyter-182872:~$ OPC_CLIENT=OpenOPC
jovyan@jupyter-182872:~$ OPC_GATE_HOST=XX.XX.XX.XX
jovyan@jupyter-182872:~$ OPC_GATE_PORT=135
jovyan@jupyter-182872:~$ OPC_HOST=localhost
jovyan@jupyter-182872:~$ OPC_MODE=dcom
jovyan@jupyter-182872:~$ OPC_SERVER=Matrikon.OPC.Simulation
jovyan@jupyter-182872:~$ python -m openopc2 server-info
[00:45:37] ERROR    Could not connect to OPC server: cannot connect to ('XX.XX.XX.XX', 7766): [Errno 110] Connection timed out       
```

Python version: 3.10.5
openopc2 version: 0.1.11
OS: Ubuntsu 20.04

Best regards.

**Comment by renzop** [comment]
Please ask programming questions in Stackoverflow.
You entered configured OPC_GATE_PORT=135 (this should be 7766), And the OPC Server should be your OPC server (unicorn) not Matrikon.
