### ISSUE TITLE
Unable to Install the OpenOPC Service

### ISSUE THREAD

**Issue by PardeepRassani** [iterativ/openopc2#51]
> You can download the executables in the repositories github page under https://github.com/iterativ/openopc2/releases/tag/0.1.11

I am trying to install openopc2 on windows server 2019, I have download the three exe files, and tried to install OPC service by running `openopcservice install` and then `openopcservice start`  in the terminal, however it doesn't create OpenOPC directory in C drive, nor opc comand works in cmd. 

What am I missing please?

_Originally posted by @PardeepRassani in https://github.com/iterativ/openopc2/discussions/4#discussioncomment-6563345_

**Comment by renzop** [comment]
It does not need to create any folders.
openopcservice is a windows service with no other commands except install, start, stop, restart.
