### ISSUE TITLE
Unable to establish connection with the server

### ISSUE THREAD

**Issue by Rahul14189** [iterativ/openopc2#57]
Hi, I am using Kepware Server Simulator on my local machine, and then i am trying to connect with the simulated server using OpenOPC but it throws error and does not allow to connect, whereas using metrikon i can see tags !

if i use open gateway service (open mode), then it throws following error:
![image](https://github.com/iterativ/openopc2/assets/99563180/da43f5d9-576d-4cd0-8efc-7287296ff44e)

And if i use DCOM mode, then it return FALSE,

And sometimes while using DCOM mode, it throws following error:
![image](https://github.com/iterativ/openopc2/assets/99563180/12e57f53-43a2-41ca-a48b-4abc51a58727)

Following is my code in DCOM mode:
![image](https://github.com/iterativ/openopc2/assets/99563180/7ebca16e-08bf-4a0b-b2a2-14d822e06853)

And in open mode following is my code:
![image](https://github.com/iterativ/openopc2/assets/99563180/aa75c667-f503-477b-9ba3-7bf715339ddf)

Do you have any idea on what I could be doing wrong?

**Comment by renzop** [comment]
Your code shows that you are using another library.. 
This is openopc2
