### ISSUE TITLE
MemoryError on long-lasting session

### ISSUE THREAD

**Issue by Th-Havy** [iterativ/openopc2#58]
**Describe the bug**
I have a production script that should run forever and interacts with some instruments using OpenOPC2. Over time, the amount of memory used by the program keeps increasing, eventually causing a `MemoryError`.

**To Reproduce**
Here is a minimal script to reproduce the issue:
```python
opc = OpenOPC.client()
opc.connect("OPC.SimaticNET")
while True: 
    reply = opc.read(arg)  # Memory leak here?
```

**Expected behavior**
This scripts should not cause any increase in memory usage.

**Screenshots**
Here is the console output of the error:
```
File "...........\lib\site-packages\OpenOPC.py", line 625, in read
    return list(results)
  File "...........\lib\site-packages\OpenOPC.py", line 454, in iread
    valid_tags, server_handles = add_items(tags)
  File "...........\lib\site-packages\OpenOPC.py", line 321, in add_items
    self._group_handles_tag[sub_group][n] = tag
MemoryError
```

**Possible cause**
According to the error message above, it seems that the dictionnary `self._group_handles_tag[sub_group]` (OpenOPC.py", line 321) keeps increasing in size at every read. Maybe a maximum size should be defined after which the dict should be emptied or the existing entries should be re-used (similar to a circular buffer).

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - OPC Server: 0.1.11
 - Python Version: 3.8
 - Environment Variables

Thanks in advance!

**Comment by renzop** [comment]
I think you reported an issue of the the old openopc library. The file  "OpenOPC.py" you are mentioning does not exist in this Library. 
Please perform the same same test with this library.
