### ISSUE TITLE
I cannot start openopc gateway service

### ISSUE THREAD

**Issue by caoqianming** [iterativ/openopc2#60]
![image](https://github.com/iterativ/openopc2/assets/21101210/6e950251-22f0-450b-97d8-895664c769dd)
the install command work but cannot start, In windows services I the openopc gateway service dont work.
I use windows 11 64
![image](https://github.com/iterativ/openopc2/assets/21101210/7df7e358-1409-4e0e-bfdb-20cb3b02f2d8)

**Comment by Tracersboy** [comment]
i have the same question

**Comment by caoqianming** [comment]
> i have the same question

用opcua吧，更好。

**Comment by Tracersboy** [comment]
我知道了，得在系统环境变量里面配置下host。临时和用户环境变量都不行，因为服务是用系统启动的

**Comment by caoqianming** [comment]
好的，感谢



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 26, 2024 17:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [iterativ/openopc2] I cannot start openopc gateway service (Issue#60)




 
我知道了，得在系统环境变量里面配置下host。临时和用户环境变量都不行，因为服务是用系统启动的

**Comment by renzop** [comment]
Please write the issues and comments in english.

**Comment by renzop** [comment]
This is related to  #64
